FROM nginx:1.18-alpine

RUN apk add --no-cache python3 py3-pip uwsgi-python3 python3-dev g++

WORKDIR /app

COPY nginx.conf /etc/nginx/nginx.conf
COPY uwsgi.ini ./

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

COPY . ./

COPY entrypoint.sh /

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx-debug", "-g", "daemon off;"]