FROM nginx:1.18-alpine

RUN apk add --no-cache python3 py3-pip uwsgi-python3 python3-dev g++ postgresql-dev \
    musl-dev libffi-dev openssl-dev cargo

RUN apk upgrade
RUN pip3 install --upgrade pip

WORKDIR /app

COPY /projects/mibs/nginx.conf /etc/nginx/nginx.conf
COPY /projects/mibs/uwsgi.ini ./

COPY /projects/mibs/requirements.txt ./
RUN pip3 install -r requirements.txt

ENV PYTHONPATH="$PYTHONPATH:/app/lib/auth"
COPY /lib/flask-auth/ /app/lib/auth

COPY /projects/mibs/. ./

COPY /projects/mibs/entrypoint.sh /

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx-debug", "-g", "daemon off;"]