"""added schools table

Revision ID: 9941b1698eac
Revises: 0bba3a6734fb
Create Date: 2021-10-14 12:53:54.113578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9941b1698eac'
down_revision = '0bba3a6734fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('students', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools')
    # ### end Alembic commands ###
