FROM node:16-alpine as build
WORKDIR /app
COPY . .
RUN npm build && npm install

FROM nginx:1.18-alpine
EXPOSE 80
COPY - from=build /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
