#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE mibs OWNER $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE mibs TO $POSTGRES_USER;
EOSQL
