FROM nginx:1.18-alpine

RUN apk add --no-cache python3 py3-pip uwsgi-python3

WORKDIR /app

COPY nginx.conf /etc/nginx/nginx.conf
COPY uwsgi.ini ./

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

COPY . ./

COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]